import Head from "next/head";
import styles from "@/styles/Home.module.css";
import AcomponenteTopo from "./ComponentesOtica/AcomponenteTopo/Topo";
import BcomponenteBanner from "./ComponentesOtica/BcomponenteBanner/Banner";
import CcomponenteProdutos from "./ComponentesOtica/CcomponenteProdutos/Produtos";
import DcomponenteSobre from "./ComponentesOtica/DcomponenteSobre/Sobre";
import EcomponenteContato from "./ComponentesOtica/EcomponenteContato/Comtato";
import FcomponenteRodape from "./ComponentesOtica/FcomponenteRodape/Rodape";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AcomponenteTopo/>
      <main>
        <BcomponenteBanner/>
        <CcomponenteProdutos/>
        <DcomponenteSobre/>
        <EcomponenteContato/>
        <FcomponenteRodape/>
      </main>
      </>
  );
}
