import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home(){
  return(
    <div>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.containerTopo}>
        <h1 className={styles.containerTopoTitulo}>React JS</h1>
      </header>
      <main>
        <section className={styles.containerIntroducao}>
          <h2 className={styles.containerIntroducaoSubtitulo}>React JS</h2>
          <p className={styles.containerIntroducaoParagrafo}>Biblioteca JavaScript para criar SPAs</p>
          <a className={styles.containerIntroducaoLink} href="https://reactjs.org/">Site Oficial</a>
        </section>
        <section className={styles.containerRequisitos}>
          <div className={styles.containerRequisitosdiv1}>
            <h3>Requisitos</h3>
            <p>Veja abaixo os requisitos mínimos para aprender React JS:</p>
          </div>
          <div className={styles.containerRequisitosdiv2}>
            <div className={styles.containerRequisitosCards}>
              <h3>HTML</h3>
              <p>Aprender a estruturar os elementos da página com HTML</p>
            </div>
            <div className={styles.containerRequisitosCards}>
              <h3>CSS</h3>
              <p>Aprender a estilizar os elementos da página com CSS</p>
            </div>
            <div className={styles.containerRequisitosCards}>
              <h3>JavaScript</h3>
              <p>Aprender a linguagem utilizada pelo React JS, o JavaScript</p>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.containerRodape}>
        <p>Curso de introdução de React JS</p>
      </footer>
    </div>
  )
}